-- =============================================================================
-- SSR ONE AI – CLOUD / REMOTE POSTGRESQL PRODUCTION MIGRATION SCRIPT
-- Generated by exact schema comparison between Local DB and Neon Cloud DB
-- Safe and Idempotent (IF NOT EXISTS)
-- =============================================================================

-- ─── 1. DDL: ADD MISSING COLUMNS TO TABLES ──────────────────────────────────

-- Menu Categories: Photography Image Support
ALTER TABLE menu_categories ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);

-- KOT Items: Multi-Tenant & KDS Line-Item Tracking
ALTER TABLE kot_items ADD COLUMN IF NOT EXISTS branch_id BIGINT DEFAULT 1;
ALTER TABLE kot_items ADD COLUMN IF NOT EXISTS company_id BIGINT DEFAULT 1;
ALTER TABLE kot_items ADD COLUMN IF NOT EXISTS notes VARCHAR(255);
ALTER TABLE kot_items ADD COLUMN IF NOT EXISTS order_item_id BIGINT;

-- KOTs (Kitchen Order Tickets): Branch Isolation & Thermal Print Timestamp
ALTER TABLE kots ADD COLUMN IF NOT EXISTS branch_id BIGINT DEFAULT 1;
ALTER TABLE kots ADD COLUMN IF NOT EXISTS printed_at VARCHAR(255);

-- Order Payments: Branch Scope
ALTER TABLE order_payments ADD COLUMN IF NOT EXISTS branch_id BIGINT DEFAULT 1;

-- Order Status Logs: Event Audit, Tracking & Correlation
ALTER TABLE order_status_logs ADD COLUMN IF NOT EXISTS old_status VARCHAR(255);
ALTER TABLE order_status_logs ADD COLUMN IF NOT EXISTS event_type VARCHAR(255);
ALTER TABLE order_status_logs ADD COLUMN IF NOT EXISTS payload VARCHAR(255);
ALTER TABLE order_status_logs ADD COLUMN IF NOT EXISTS correlation_id VARCHAR(255);
ALTER TABLE order_status_logs ADD COLUMN IF NOT EXISTS notes VARCHAR(255);

-- ─── 2. DATA BACKFILL: DEFAULT NULL BRANCH/COMPANY SCOPES ────────────────────

UPDATE kot_items SET branch_id = 1 WHERE branch_id IS NULL;
UPDATE kot_items SET company_id = 1 WHERE company_id IS NULL;
UPDATE kots SET branch_id = 1 WHERE branch_id IS NULL;
UPDATE order_payments SET branch_id = 1 WHERE branch_id IS NULL;

-- ─── 3. MENU CATEGORIES: ARTISAN FOOD PHOTOGRAPHY IMAGES ────────────────────

UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=400&q=80' WHERE id = 1; -- Momo''s
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=400&q=80' WHERE id = 2; -- Roll
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=400&q=80' WHERE id = 3; -- Noodles & Rice
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=400&q=80' WHERE id = 4; -- Others
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80' WHERE id = 5; -- French
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=400&q=80' WHERE id = 6; -- Fries & Pasta
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=400&q=80' WHERE id = 7; -- Pizza
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=400&q=80' WHERE id = 8; -- Drink
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=400&q=80' WHERE id = 9; -- Tandoori
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=400&q=80' WHERE id = 10; -- Sabji
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80' WHERE id = 11; -- Special Paneer
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=400&q=80' WHERE id = 12; -- Breads
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=400&q=80' WHERE id = 13; -- Paratha, South-Ind
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80' WHERE id = 14; -- RRP
UPDATE menu_categories SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=400&q=80' WHERE id = 15; -- Thali, Combo

-- ─── 4. MENU ITEMS: POPULATE HIGH-RES DISH PHOTOGRAPHY IMAGES ───────────────

UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=500&q=80' WHERE id = 1; -- Veg. Steam Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=500&q=80' WHERE id = 2; -- Veg. Fry Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=500&q=80' WHERE id = 3; -- Veg. Butter Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=500&q=80' WHERE id = 4; -- Veg. Kurkure Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=500&q=80' WHERE id = 5; -- Veg. Tandoori Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 6; -- Veg. Malai Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=500&q=80' WHERE id = 7; -- Veg. Afgani Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=500&q=80' WHERE id = 8; -- Veg. Chilli Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=500&q=80' WHERE id = 9; -- Paneer Steam Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1526318896980-cf78c088247c?auto=format&fit=crop&w=500&q=80' WHERE id = 10; -- Paneer Fry Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=500&q=80' WHERE id = 11; -- Paneer Butter Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=500&q=80' WHERE id = 12; -- Paneer Kurkure Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&w=500&q=80' WHERE id = 13; -- Paneer Tandoori Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 14; -- Paneer Malai Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=500&q=80' WHERE id = 15; -- Paneer Afgani Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=500&q=80' WHERE id = 16; -- Paneer Chilli Momos
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=500&q=80' WHERE id = 17; -- Veg. Spring Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?auto=format&fit=crop&w=500&q=80' WHERE id = 18; -- Paneer Spring Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=500&q=80' WHERE id = 19; -- Mix Spring Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=500&q=80' WHERE id = 20; -- Veg. Kathi Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=500&q=80' WHERE id = 21; -- Noodle Kathi Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 22; -- Paneer Kathi Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=500&q=80' WHERE id = 23; -- Mix Kathi Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=500&q=80' WHERE id = 24; -- Tandoori Chaap Kathi Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=500&q=80' WHERE id = 25; -- Tandoori Malai Chaap Kathi Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=500&q=80' WHERE id = 26; -- Tandoori Afgani Chaap Kathi Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 27; -- Tandoori Paneer Tikka Kathi Roll
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=500&q=80' WHERE id = 28; -- Veg. Noodles
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=500&q=80' WHERE id = 29; -- Schezwan Noodles
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=500&q=80' WHERE id = 30; -- Chilli Garlic Noodles
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=500&q=80' WHERE id = 31; -- Singapuri Noodles
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=500&q=80' WHERE id = 32; -- Paneer Noodles
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=500&q=80' WHERE id = 33; -- Hakka Noodles
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1541696432-82c6da8ce7bf?auto=format&fit=crop&w=500&q=80' WHERE id = 34; -- Special Veg. Loaded Noodles
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=500&q=80' WHERE id = 35; -- Veg. Fried Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=500&q=80' WHERE id = 36; -- Manchurian Fried Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?auto=format&fit=crop&w=500&q=80' WHERE id = 37; -- Paneer Fried Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=500&q=80' WHERE id = 38; -- Schezwan Fried Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=500&q=80' WHERE id = 39; -- Chilli Garlic Fried Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=500&q=80' WHERE id = 40; -- Singapuri Fried Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=500&q=80' WHERE id = 41; -- Special Veg. Loaded Fried Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&w=500&q=80' WHERE id = 42; -- Veg. Hot & Sour Soup
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1604152135912-04a022e23696?auto=format&fit=crop&w=500&q=80' WHERE id = 43; -- Sweet Corn Soup
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=500&q=80' WHERE id = 44; -- Manchow Soup
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=500&q=80' WHERE id = 45; -- Peanut Masala
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=500&q=80' WHERE id = 46; -- Sweet Corn Chaat
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?auto=format&fit=crop&w=500&q=80' WHERE id = 47; -- Crispy Corn Chaat
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=500&q=80' WHERE id = 48; -- Pav Bhaji
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=500&q=80' WHERE id = 49; -- Veg. Fried Rice & Manchurian Gravy
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=500&q=80' WHERE id = 50; -- Veg. Noodle & Manchurian Gravy
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&w=500&q=80' WHERE id = 51; -- Extra Loaded Veg Maggie
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=500&q=80' WHERE id = 52; -- Veg Sandwich
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1553909489-cd47e0907980?auto=format&fit=crop&w=500&q=80' WHERE id = 53; -- Paneer Sandwich
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=500&q=80' WHERE id = 54; -- Tandoori Sandwich
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1528736235302-52922df5c122?auto=format&fit=crop&w=500&q=80' WHERE id = 55; -- Cheese Sandwich
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=500&q=80' WHERE id = 56; -- Aloo Tikki Burger
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=500&q=80' WHERE id = 57; -- Veggie Burger
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=500&q=80' WHERE id = 58; -- Paneer Burger
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=500&q=80' WHERE id = 59; -- Cheese Burger
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=500&q=80' WHERE id = 60; -- Melted Cheese Burger
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=500&q=80' WHERE id = 61; -- Maharaja Burger
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=500&q=80' WHERE id = 62; -- Aloo Tikki Wrap
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=500&q=80' WHERE id = 63; -- Veggie Wrap
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=500&q=80' WHERE id = 64; -- Paneer Wrap
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=500&q=80' WHERE id = 65; -- Melted Cheese Wrap
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=500&q=80' WHERE id = 66; -- French Fries
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=500&q=80' WHERE id = 67; -- Peri Peri Fries
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1518013031184-41d4bf22045e?auto=format&fit=crop&w=500&q=80' WHERE id = 68; -- Chilli Potato
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1518013031184-41d4bf22045e?auto=format&fit=crop&w=500&q=80' WHERE id = 69; -- Honey Chilli Potato
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=500&q=80' WHERE id = 70; -- Manchurian Dry
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=500&q=80' WHERE id = 71; -- Manchurian Gravy
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 72; -- Paneer Chilli Dry
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 73; -- Paneer Chilli Gravy
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 74; -- Mushroom Chilli Dry
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 75; -- Gobi Chilli Dry
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 76; -- Soya Chilli Dry
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=500&q=80' WHERE id = 77; -- Red Sauce Pasta
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=500&q=80' WHERE id = 78; -- White Sauce Pasta
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=500&q=80' WHERE id = 79; -- Mix Sauce Pasta
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=500&q=80' WHERE id = 80; -- Sweet Corn Pasta
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=500&q=80' WHERE id = 81; -- Paneer Pasta
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=500&q=80' WHERE id = 82; -- Special Veg. Loaded Pasta
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=500&q=80' WHERE id = 83; -- Sweet Corn / Capsicum / Onion / Tomato Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=500&q=80' WHERE id = 84; -- Veg Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=500&q=80' WHERE id = 85; -- Margherita Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=500&q=80' WHERE id = 86; -- Black Olive Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=500&q=80' WHERE id = 87; -- Mushroom Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=500&q=80' WHERE id = 88; -- Paneer Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=500&q=80' WHERE id = 89; -- Peppy Paneer Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=500&q=80' WHERE id = 90; -- Tandoori Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=500&q=80' WHERE id = 91; -- Indi Tandoori Paneer Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=500&q=80' WHERE id = 92; -- Farm House Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=500&q=80' WHERE id = 93; -- Double Decker Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=500&q=80' WHERE id = 94; -- All in One Pizza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=500&q=80' WHERE id = 95; -- Chai
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=500&q=80' WHERE id = 96; -- Black Coffee
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=500&q=80' WHERE id = 97; -- Coffee
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=500&q=80' WHERE id = 98; -- Coke
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&w=500&q=80' WHERE id = 99; -- Strawberry Ice Cream
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=500&q=80' WHERE id = 100; -- Chocolate Ice Cream
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1570197788417-0e82375c9371?auto=format&fit=crop&w=500&q=80' WHERE id = 101; -- Butterscotch Ice Cream
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1580915411954-282cb1b0d780?auto=format&fit=crop&w=500&q=80' WHERE id = 102; -- Kesar Pista Ice Cream
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=500&q=80' WHERE id = 103; -- Banana Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=500&q=80' WHERE id = 104; -- Papaya Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=500&q=80' WHERE id = 105; -- Mango Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=500&q=80' WHERE id = 106; -- Chikoo Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=500&q=80' WHERE id = 107; -- Mix Shake (Banana, Papaya, Chikoo)
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=500&q=80' WHERE id = 108; -- Cold Coffee
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=500&q=80' WHERE id = 109; -- Strawberry Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=500&q=80' WHERE id = 110; -- Butterscotch Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?auto=format&fit=crop&w=500&q=80' WHERE id = 111; -- Vanilla Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=500&q=80' WHERE id = 112; -- Chocolate Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=500&q=80' WHERE id = 113; -- Chocolate + Banana Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=500&q=80' WHERE id = 114; -- Kitkat Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=500&q=80' WHERE id = 115; -- Oreo Shake
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=500&q=80' WHERE id = 116; -- Virgin Mojito
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=500&q=80' WHERE id = 117; -- Blue Lagoon Mojito
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1536935338788-846bb9981813?auto=format&fit=crop&w=500&q=80' WHERE id = 118; -- Green Apple Mojito
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=500&q=80' WHERE id = 119; -- Kala Khatta Mojito
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1500217052183-bc01ebd1a74e?auto=format&fit=crop&w=500&q=80' WHERE id = 120; -- Strawberry Mojito
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=500&q=80' WHERE id = 121; -- Guava Mojito
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=500&q=80' WHERE id = 122; -- Orange Mojito
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1587223962930-cb7f31384c19?auto=format&fit=crop&w=500&q=80' WHERE id = 123; -- Pineapple Mojito
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=500&q=80' WHERE id = 124; -- Masala Chaap
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=500&q=80' WHERE id = 125; -- Achari Chaap
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=500&q=80' WHERE id = 126; -- Malai Chaap
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=500&q=80' WHERE id = 127; -- Afgani Chaap
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=500&q=80' WHERE id = 128; -- Hara Bhara Kebab (6 Pcs)
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=500&q=80' WHERE id = 129; -- Veg. Seekh Kebab (2 Pcs)
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=500&q=80' WHERE id = 130; -- Reshmi Kebab (6 Pcs)
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=500&q=80' WHERE id = 131; -- Dahi Ke Sholay (2 Pcs)
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=400&q=80' WHERE id = 132; -- Tandoori Aloo Tikka
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 133; -- Paneer Tikka
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 134; -- Achari Paneer Tikka
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 135; -- Malai Paneer Tikka
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 136; -- Mushroom Tikka
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 137; -- Dahi Fry
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 138; -- Dal Fry (Yellow / Mix)
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 139; -- Butter Fry Dal
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=500&q=80' WHERE id = 140; -- Dal Makhani
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 141; -- Aloo Matar
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 142; -- Gobhi Matar
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80' WHERE id = 143; -- Chole Masala
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 144; -- Punjabi Rajma
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 145; -- Mix Veg
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 146; -- Matar Mushroom
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 147; -- Mushroom Masala
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 148; -- Jeera Aloo
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 149; -- Sev Bhaji
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 150; -- Aloo Gobhi
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=500&q=80' WHERE id = 151; -- Malai Kofta
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 152; -- Stuffed Capsicum
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 153; -- Cheese Tomato
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=500&q=80' WHERE id = 154; -- Navratan Korma
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 155; -- Kashmiri Dum Aloo
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 156; -- Kaju Curry
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=500&q=80' WHERE id = 157; -- Masala Chaap Gravy
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=500&q=80' WHERE id = 158; -- Rogan Josh Chaap Gravy
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?auto=format&fit=crop&w=500&q=80' WHERE id = 159; -- Butter Masala Chaap Gravy
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 160; -- Matar Paneer
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 161; -- Shahi Paneer
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 162; -- Kadai Paneer
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 163; -- Palak Paneer
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 164; -- Paneer Butter Masala
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 165; -- Paneer Lababdar
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 166; -- Paneer Do Pyaza
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?auto=format&fit=crop&w=500&q=80' WHERE id = 167; -- Paneer Tikka Masala
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 168; -- Paneer Bhurji
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 169; -- Handi Paneer
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=500&q=80' WHERE id = 170; -- Paneer Korma
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 171; -- Hyderabadi Paneer
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 172; -- Paneer Pasanda
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=500&q=80' WHERE id = 173; -- Green Salad
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=500&q=80' WHERE id = 174; -- Kachumber Salad
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=500&q=80' WHERE id = 175; -- Fruit Salad
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 176; -- Tawa Roti
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 177; -- Tawa Butter Roti
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 178; -- Tandoori Roti
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 179; -- Tandoori Butter Roti
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 180; -- Tandoori Onion Roti (Butter)
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=500&q=80' WHERE id = 181; -- Lachha Paratha
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 182; -- Plain Naan
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 183; -- Butter Naan
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 184; -- Garlic Butter Naan
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 185; -- Aloo Stuffed Naan
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 186; -- Paneer Stuffed Naan
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 187; -- Missi Roti (Onion)
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=500&q=80' WHERE id = 188; -- Aloo Paratha
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=500&q=80' WHERE id = 189; -- Aloo-Pyaaz Paratha
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=500&q=80' WHERE id = 190; -- Pyaaz Paratha
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=500&q=80' WHERE id = 191; -- Gobi Paratha
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 192; -- Paneer Paratha
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=500&q=80' WHERE id = 193; -- Mix Paratha
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80' WHERE id = 194; -- Plain Dosa
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80' WHERE id = 195; -- Masala Dosa
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80' WHERE id = 196; -- Onion Dosa
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 197; -- Paneer Dosa
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80' WHERE id = 198; -- Idli Sambar
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80' WHERE id = 199; -- Vada Sambar
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 200; -- Plain Dahi
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 201; -- Boondi Raita
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 202; -- Mix Veg. Raita
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 203; -- Kachumber Raita
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 204; -- Aloo Raita
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 205; -- Mix Fruit Raita
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=500&q=80' WHERE id = 206; -- Masala Chaach
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=500&q=80' WHERE id = 207; -- Sweet Lassi
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 208; -- Roasted Papad
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 209; -- Fry Papad
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 210; -- Masala Papad
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=500&q=80' WHERE id = 211; -- Plain Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=500&q=80' WHERE id = 212; -- Jeera Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=500&q=80' WHERE id = 213; -- Matar Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=500&q=80' WHERE id = 214; -- Tomato Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=500&q=80' WHERE id = 215; -- Curd Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=500&q=80' WHERE id = 216; -- Veg. Pulao
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=500&q=80' WHERE id = 217; -- Kashmiri Pulao
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=500&q=80' WHERE id = 218; -- Special Veg. Biryani
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80' WHERE id = 219; -- Chole Masala + Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=500&q=80' WHERE id = 220; -- Punjabi Rajma + Rice
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 221; -- Shahi Paneer + 2 Lachha Paratha
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=500&q=80' WHERE id = 222; -- Dal Makhani + 4 Tandoori Roti
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 223; -- Aloo Chur-Chur Naan Thali
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 224; -- Aloo-Pyaaz Chur-Chur Naan Thali
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 225; -- Gobi Chur-Chur Naan Thali
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=500&q=80' WHERE id = 226; -- Paneer Chur-Chur Naan Thali
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=500&q=80' WHERE id = 227; -- Mix Chur-Chur Naan Thali
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80' WHERE id = 228; -- Mini Thali
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=500&q=80' WHERE id = 229; -- Baithak Special Thali
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?auto=format&fit=crop&w=500&q=80' WHERE id = 230; -- Dew
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=500&q=80' WHERE id = 231; -- Nimbu Pani
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=500&q=80' WHERE id = 232; -- Pav Only
UPDATE menu_items SET image_url = 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=500&q=80' WHERE id = 233; -- Cake

-- =============================================================================
-- MIGRATION COMPLETE
-- =============================================================================